name: refitt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - matplotlib
  - pandas
  - h5py
  - xlrd
  - pyyaml
  - yaml
  - sqlalchemy
  - psycopg2
  - paramiko
  - flask
  - keras
  - tensorflow
  - ipython
  - sphinx
  - pytest
  - hypothesis
  - pylint
  - pip
  - pip:
    - antares-client
    - cmdkit>=1.1.0
    - gunicorn
    - logalpha>=2.0.0
    - slackclient
    - sphinx-rtd-theme
    - sshtunnel
    - tabulate
